import type { ComponentType } from "react";
import type { UserMood, ThemeCategory } from "./types";

import {
  BookOpen,
  BookMarked,
  RotateCcw,
  Notebook,
  Target,
  FileText,
  Library,
  ClipboardCheck,
  Headphones,
  Mic,
  Layers,
  Podcast,
  Radio,
  GraduationCap,
  Briefcase,
  Film,
  Bot,
  Terminal,
  Code,
  Workflow,
  FileStack,
  GitBranch,
  Wrench,
  Zap,
  Activity,
  Footprints,
  Accessibility,
  TreePine,
  Sun,
  Heart,
  Timer,
  Utensils,
  Moon,
  Sunrise,
  BedDouble,
  Flower2,
  Droplets,
  CupSoda,
  ChefHat,
  Eye,
  HeartHandshake,
  Book,
  Clock,
  Brain,
  Sparkles,
  Coffee,
  Wind,
  Trash2,
  Home,
  Monitor,
  Shirt,
  PackageOpen,
  Building2,
  SprayCan,
  Smartphone,
  Laptop,
  Paintbrush,
  Camera,
  UtensilsCrossed,
  Palette,
  Music,
  Clapperboard,
  NotebookPen,
  Users,
  ThumbsUp,
  Star,
  Ear,
  Globe,
  MessageSquare,
  Compass,
  FolderOpen,
  Mail,
  PiggyBank,
  ShoppingBag,
  Package,
  Box,
  Wallet,
  Trees,
  Store,
  Building,
  Train,
  ShoppingBasket,
  Map as MapIcon,
  BatteryLow,
  TimerOff,
  ChevronRight,
  Shield,
  Bed,
  LifeBuoy,
  Sprout,
  Languages,
  Flame,
  HeartPulse,
  type LucideProps,
} from "lucide-react";

// ── Theme icon names → lucide components ──

const ICON_COMPONENTS: Record<string, ComponentType<LucideProps>> = {
  BookOpen, BookMarked, RotateCcw, Notebook, Target, FileText,
  Library, ClipboardCheck, Headphones, Mic, Layers, Podcast,
  Radio, GraduationCap, Briefcase, Film, Bot, Terminal, Code,
  Workflow, FileStack, GitBranch, Wrench, Zap, Activity,
  Footprints, Accessibility, TreePine, Sun, Heart, Timer,
  Utensils, Moon, Sunrise, BedDouble, Flower2, Droplets,
  CupSoda, ChefHat, Eye, HeartHandshake, Book, Clock, Brain,
  Sparkles, Coffee, Wind, Trash2, Home, Monitor, Shirt,
  PackageOpen, Building2, SprayCan, Smartphone, Laptop,
  Paintbrush, Camera, Mug: CupSoda, UtensilsCrossed, Palette, Music,
  Clapperboard, NotebookPen, Users, ThumbsUp, Star, Ear,
  Globe, MessageSquare, Compass, FolderOpen, Mail, PiggyBank,
  ShoppingBag, Package, Box, Wallet, Trees, Store, Building,
  Train, ShoppingBasket, Map: MapIcon, BatteryLow, TimerOff, ChevronRight,
  Shield, Bed, LifeBuoy, Sprout, Languages,
};

/** Resolve a theme icon name string → lucide component. Falls back to Sparkles. */
export function getIconComponent(name: string): ComponentType<LucideProps> {
  return ICON_COMPONENTS[name] || Sparkles;
}

// ── Mood icons ──

export const MOOD_ICON: Record<UserMood, ComponentType<LucideProps>> = {
  tired: Moon,
  wantDiscipline: Flame,
  wantStudy: BookOpen,
  wantEnglish: Languages,
  wantHealth: HeartPulse,
  wantFun: Sparkles,
  wantOrganize: Home,
  wantJob: Briefcase,
};

// ── Category icons ──

export const CATEGORY_ICON: Record<ThemeCategory, ComponentType<LucideProps>> = {
  "学习成长": BookOpen,
  "英语提升": Languages,
  "AI与技能": Bot,
  "健康运动": Activity,
  "养生作息": Moon,
  "情绪疗愈": HeartHandshake,
  "生活整理": Home,
  "兴趣探索": Paintbrush,
  "社交关系": Users,
  "工作实习": Briefcase,
  "省钱理财": PiggyBank,
  "城市探索": MapIcon,
  "低能量恢复": BatteryLow,
};
