import type { ThemeTemplate, ThemeCategory } from "./types";

export const THEME_TEMPLATES: ThemeTemplate[] = [
  // ═══════════════════════════════════════════════════════════
  // 学习成长
  // ═══════════════════════════════════════════════════════════
  {
    id: "reading-week",
    title: "阅读周",
    category: "学习成长",
    description: "每天安排固定时间读书，培养持续阅读习惯。",
    suitableFor: ["想增加阅读量但总说没时间", "买了很多书却没翻开过", "想建立稳定阅读节奏"],
    weeklyGoal: "读完一本书或累计阅读 5 小时以上",
    dailyAction: "每天阅读 30 分钟以上，记录一句最有感触的话",
    minimumStandard: "每天至少读 10 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["这周读的书让你收获了什么？", "哪个时间段最专注？", "下周想读什么类型的书？"],
    tags: ["阅读", "输入", "专注"],
    icon: "BookOpen",
    color: "#6366F1",
  },
  {
    id: "preview-week",
    title: "预习周",
    category: "学习成长",
    description: "提前预习课程内容，带着问题去上课，学习效率翻倍。",
    suitableFor: ["上课听不懂跟不上的学生", "想提前了解课程框架", "想提高课堂参与度"],
    weeklyGoal: "预习完下周全部课程内容",
    dailyAction: "每次课前花 20 分钟预习，标注不懂的地方",
    minimumStandard: "至少预习 3 次",
    checkInType: "次数",
    reviewQuestions: ["预习后上课感觉有什么不同？", "哪些科目预习效果最好？", "下周的预习计划需要调整吗？"],
    tags: ["课程", "预习", "学习习惯"],
    icon: "BookMarked",
    color: "#818CF8",
  },
  {
    id: "review-week",
    title: "复习周",
    category: "学习成长",
    description: "系统回顾本周所学内容，巩固记忆，防止学了就忘。",
    suitableFor: ["学完就忘", "知识体系混乱", "想提高长期记忆效果"],
    weeklyGoal: "复习本周全部核心知识点，整理出复习笔记",
    dailyAction: "每天复习一个科目的重点内容，做 3 道练习题",
    minimumStandard: "每天至少复习 15 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["哪些知识点掌握得最牢固？", "哪些还需要再花时间？", "什么复习方法最有效？"],
    tags: ["复习", "巩固", "记忆"],
    icon: "RotateCcw",
    color: "#A78BFA",
  },
  {
    id: "note-organization-week",
    title: "笔记整理周",
    category: "学习成长",
    description: "清理和重构你的学习笔记，让知识更有条理、更容易回顾。",
    suitableFor: ["笔记散乱没有体系", "记了很多但从不回头看", "想建立自己的知识库"],
    weeklyGoal: "整理完本周/本月的所有笔记，建立分类体系",
    dailyAction: "每天整理一个科目的笔记，优化结构和重点标注",
    minimumStandard: "至少整理 20 页笔记",
    checkInType: "页数",
    reviewQuestions: ["笔记整理前后对比有什么变化？", "哪种笔记结构最适合你？", "以后怎么保持笔记整洁？"],
    tags: ["笔记", "整理", "知识管理"],
    icon: "Notebook",
    color: "#C4B5FD",
  },
  {
    id: "finals-sprint-week",
    title: "期末冲刺周",
    category: "学习成长",
    description: "考前集中冲刺，高效复习，用最少的时间拿最多的分。",
    suitableFor: ["期末考试即将来临", "还有很多内容没复习", "需要高强度突击"],
    weeklyGoal: "完成所有科目的重点复习和真题练习",
    dailyAction: "每天攻克一个科目的重点章节，做一套真题",
    minimumStandard: "每天至少专注学习 4 小时",
    checkInType: "时长(小时)",
    reviewQuestions: ["哪些科目复习得最充分？", "考试策略有什么需要改进的？", "这周的冲刺方法可以复用吗？"],
    tags: ["考试", "冲刺", "高效"],
    icon: "Target",
    color: "#F472B6",
  },
  {
    id: "output-week",
    title: "输出周",
    category: "学习成长",
    description: "把学到的知识用自己的话输出，真正内化。写作、讲解、分享都可以。",
    suitableFor: ["只会输入不会输出", "想锻炼表达能力", "想检验自己真正理解了多少"],
    weeklyGoal: "完成 3 篇学习总结或 1 次分享讲解",
    dailyAction: "每天写 200 字学习总结，或录制 3 分钟讲解视频",
    minimumStandard: "每天至少写 100 字",
    checkInType: "字数",
    reviewQuestions: ["输出过程中最大的困难是什么？", "哪种输出形式最适合你？", "输出的内容质量是否满意？"],
    tags: ["输出", "表达", "内化"],
    icon: "FileText",
    color: "#FB7185",
  },
  {
    id: "library-week",
    title: "图书馆周",
    category: "学习成长",
    description: "每天去图书馆/自习室学习，利用环境提升专注力。",
    suitableFor: ["在家学不进去", "总被手机分心", "想体验沉浸式学习"],
    weeklyGoal: "在图书馆完成 5 次以上的深度学习",
    dailyAction: "去图书馆专注学习至少 2 小时，手机放包里",
    minimumStandard: "至少去 3 次图书馆",
    checkInType: "次数",
    reviewQuestions: ["在图书馆和在家学习效率差多少？", "什么时间段效果最好？", "以后每周安排几次图书馆日？"],
    tags: ["自习", "专注", "环境"],
    icon: "Library",
    color: "#2DD4BF",
  },
  {
    id: "mistake-cleanup-week",
    title: "错题清理周",
    category: "学习成长",
    description: "集中清理各科错题，分析错误原因，避免重复犯错。",
    suitableFor: ["错题积压太多", "总是在同类题目上出错", "想提高考试成绩"],
    weeklyGoal: "清理 50 道以上错题，整理出错题本",
    dailyAction: "每天清理 8-10 道错题，标注错误类型和正确解法",
    minimumStandard: "每天至少清理 5 道错题",
    checkInType: "题数",
    reviewQuestions: ["最常见的错误类型是什么？", "纠错后同类题目还会再错吗？", "错题本整理方法需要改进吗？"],
    tags: ["错题", "查漏补缺", "考试"],
    icon: "ClipboardCheck",
    color: "#34D399",
  },
  // ═══════════════════════════════════════════════════════════
  // 英语提升
  // ═══════════════════════════════════════════════════════════
  {
    id: "english-input-week",
    title: "英语输入周",
    category: "英语提升",
    description: "大量接触英语内容，培养语感，积累表达。阅读、听歌、看视频都可以。",
    suitableFor: ["很久没碰英语了", "想重新培养英语感觉", "想积累地道表达"],
    weeklyGoal: "累计 5 小时英语输入，收集 30 个有用表达",
    dailyAction: "每天至少 40 分钟英语输入（阅读/听播客/看视频）+ 记录 5 个表达",
    minimumStandard: "每天至少 20 分钟输入",
    checkInType: "时长(分钟)",
    reviewQuestions: ["这周接触了哪些英语内容？", "印象最深的一个表达是什么？", "下周想尝试什么类型的输入？"],
    tags: ["英语", "输入", "语感"],
    icon: "Headphones",
    color: "#3B82F6",
  },
  {
    id: "speaking-week",
    title: "口语周",
    category: "英语提升",
    description: "每天开口说英语，克服开口恐惧，提升流利度。",
    suitableFor: ["哑巴英语、不敢开口", "口语卡顿不流畅", "想提升口语表达"],
    weeklyGoal: "完成 7 次口语练习，每次至少 5 分钟",
    dailyAction: "每天找一个话题自言自语 5 分钟，或与 AI 对话练习",
    minimumStandard: "每天至少说 3 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["开口说英语的感觉有什么变化？", "哪些话题说起来最顺？", "下周怎么继续练口语？"],
    tags: ["英语", "口语", "表达"],
    icon: "Mic",
    color: "#60A5FA",
  },
  {
    id: "chunks-week",
    title: "Chunks 积累周",
    category: "英语提升",
    description: "专注积累地道英语语块和搭配，让表达更自然。",
    suitableFor: ["词汇量不小但说不地道", "想积累实用表达", "想把被动词汇变主动"],
    weeklyGoal: "积累 50 个有用 chunks，每个都造一个句子",
    dailyAction: "每天收集 7-8 个 chunks，记录用法并造句",
    minimumStandard: "每天至少积累 3 个 chunks",
    checkInType: "个数",
    reviewQuestions: ["这周积累的 chunks 中哪些最实用？", "能主动用出几个？", "怎么让积累成为习惯？"],
    tags: ["英语", "chunks", "语块"],
    icon: "Layers",
    color: "#93C5FD",
  },
  {
    id: "podcast-week",
    title: "Podcast 周",
    category: "英语提升",
    description: "每天听英语播客，锻炼听力，学习地道表达和不同口音。",
    suitableFor: ["听力是薄弱项", "想接触不同口音", "想利用碎片时间学英语"],
    weeklyGoal: "听完 5 集英语播客，每集做笔记",
    dailyAction: "每天听 1 集英语播客（15-30 分钟），记录新表达",
    minimumStandard: "每天至少听 10 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["哪集播客最有趣？", "听懂了多少比例？", "下周想尝试什么主题的播客？"],
    tags: ["英语", "听力", "播客"],
    icon: "Podcast",
    color: "#2563EB",
  },
  {
    id: "shadowing-week",
    title: "Shadowing 周",
    category: "英语提升",
    description: "影子跟读法练习口语和听力，模仿母语者的语音语调。",
    suitableFor: ["发音不标准", "语调和节奏不自然", "想综合提升口语听力"],
    weeklyGoal: "完成 7 次 shadowing 练习，每次至少 10 分钟",
    dailyAction: "选一段英语音频，影子跟读 10-15 分钟，录音对比",
    minimumStandard: "每天至少跟读 5 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["跟读时最大的困难是什么？", "录音对比发现哪些问题？", "发音有进步吗？"],
    tags: ["英语", "跟读", "发音"],
    icon: "Radio",
    color: "#1D4ED8",
  },
  {
    id: "ielts-week",
    title: "雅思准备周",
    category: "英语提升",
    description: "系统准备雅思考试，每天针对一个单项进行练习。",
    suitableFor: ["计划考雅思", "想了解雅思题型", "需要系统备考计划"],
    weeklyGoal: "完成 3 套雅思真题，掌握各题型答题策略",
    dailyAction: "每天完成一个单项的练习（听说读写轮换）+ 整理错题",
    minimumStandard: "每天至少练习 1 小时",
    checkInType: "时长(小时)",
    reviewQuestions: ["哪个单项进步最大？", "哪种题型还需要加强？", "下周的备考重点是什么？"],
    tags: ["英语", "雅思", "备考"],
    icon: "GraduationCap",
    color: "#1E40AF",
  },
  {
    id: "business-english-week",
    title: "商务英语周",
    category: "英语提升",
    description: "学习职场和商务场景的英语表达，提升职业竞争力。",
    suitableFor: ["即将进入外企工作", "想提升职场英语", "需要写英文邮件和做英文汇报"],
    weeklyGoal: "掌握 30 个商务英语表达，模拟一次英文面试或汇报",
    dailyAction: "每天学习 5 个商务英语表达 + 写一封英文邮件/模拟对话",
    minimumStandard: "每天至少学习 3 个表达",
    checkInType: "个数",
    reviewQuestions: ["最常用的商务表达有哪些？", "英文邮件写作有进步吗？", "模拟面试时最紧张的是什么？"],
    tags: ["英语", "商务", "职场"],
    icon: "Briefcase",
    color: "#7C3AED",
  },
  {
    id: "tv-english-week",
    title: "美剧英语周",
    category: "英语提升",
    description: "通过看美剧学英语，学习生活中的真实表达和地道用法。",
    suitableFor: ["觉得传统学英语太枯燥", "想学更生活化的表达", "喜欢看剧但想学点东西"],
    weeklyGoal: "看完 3 集美剧，整理出 40 个地道生活表达",
    dailyAction: "每天看一集美剧（带英文字幕），记录 10-15 个有用表达",
    minimumStandard: "每天至少看 20 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["这部剧中的表达实用吗？", "发现哪些以前不知道的地道用法？", "下周继续看还是换一部？"],
    tags: ["英语", "美剧", "娱乐"],
    icon: "Film",
    color: "#6D28D9",
  },
  // ═══════════════════════════════════════════════════════════
  // AI与技能
  // ═══════════════════════════════════════════════════════════
  {
    id: "ai-learning-week",
    title: "AI 学习周",
    category: "AI与技能",
    description: "系统学习 AI 工具的使用方法和原理，跟上技术发展。",
    suitableFor: ["想学 AI 但不知从何开始", "只会用 ChatGPT 聊天", "想用 AI 提升学习工作效率"],
    weeklyGoal: "掌握 3 个 AI 工具的核心用法，完成一个 AI 小项目",
    dailyAction: "每天学习一个 AI 工具/功能，并实际动手用一次",
    minimumStandard: "每天至少花 20 分钟学习 AI",
    checkInType: "时长(分钟)",
    reviewQuestions: ["这周学到的 AI 技能哪个最实用？", "AI 对你的学习/工作效率有提升吗？", "下周想深入哪个方向？"],
    tags: ["AI", "学习", "效率"],
    icon: "Bot",
    color: "#06B6D4",
  },
  {
    id: "prompt-week",
    title: "Prompt 优化周",
    category: "AI与技能",
    description: "专门练习和优化 Prompt 编写技巧，让 AI 输出更精准。",
    suitableFor: ["用 AI 但总得不到想要的答案", "想提升 Prompt 工程能力", "想让 AI 成为真正的助手"],
    weeklyGoal: "建立自己的 prompt 模板库，包含 10 个高质量 prompt",
    dailyAction: "每天设计/优化 2 个 prompt，对比不同写法的效果",
    minimumStandard: "每天至少写 1 个新 prompt",
    checkInType: "个数",
    reviewQuestions: ["哪种 prompt 写法效果最好？", "总结出哪些 prompt 技巧？", "建立的 prompt 模板库实用吗？"],
    tags: ["AI", "Prompt", "效率"],
    icon: "Terminal",
    color: "#0891B2",
  },
  {
    id: "replit-week",
    title: "Replit 开发周",
    category: "AI与技能",
    description: "用 Replit 实践开发小项目，边做边学编程。",
    suitableFor: ["想学编程但还没开始", "有想法但不知道怎么实现", "想用 AI 辅助开发"],
    weeklyGoal: "完成一个小项目并部署上线",
    dailyAction: "每天在 Replit 上写代码至少 30 分钟，解决一个小功能",
    minimumStandard: "每天至少写 15 分钟代码",
    checkInType: "时长(分钟)",
    reviewQuestions: ["项目开发过程中最大的挑战是什么？", "AI 辅助开发的效果如何？", "下周想做什么项目？"],
    tags: ["编程", "Replit", "项目"],
    icon: "Code",
    color: "#0E7490",
  },
  {
    id: "claude-workflow-week",
    title: "Claude 工作流周",
    category: "AI与技能",
    description: "探索 Claude 的高级用法，构建个性化 AI 工作流。",
    suitableFor: ["只用 Claude 聊天太浪费", "想用 AI 自动化重复工作", "想建立自己的 AI 工作体系"],
    weeklyGoal: "搭建 3 个 Claude 自动化工作流，提升日常效率",
    dailyAction: "每天设计一个自动化场景并用 Claude 实现",
    minimumStandard: "每天至少尝试一个新用法",
    checkInType: "次数",
    reviewQuestions: ["哪个工作流最提升效率？", "Claude 在哪些场景表现最好？", "下周想继续优化哪个工作流？"],
    tags: ["AI", "Claude", "自动化"],
    icon: "Workflow",
    color: "#155E75",
  },
  {
    id: "feishu-org-week",
    title: "飞书整理周",
    category: "AI与技能",
    description: "整理飞书文档和知识库，让信息管理更高效。",
    suitableFor: ["飞书文档乱糟糟", "知识库需要重构", "想用飞书搭建个人知识系统"],
    weeklyGoal: "完成飞书知识库架构重构，整理 30 篇以上文档",
    dailyAction: "每天整理一个分类的文档，建立标签和目录体系",
    minimumStandard: "每天至少整理 3 篇文档",
    checkInType: "篇数",
    reviewQuestions: ["飞书文档结构现在清晰了吗？", "标签体系合理吗？", "以后怎么保持文档整洁？"],
    tags: ["飞书", "整理", "知识管理"],
    icon: "FileStack",
    color: "#1E3A5F",
  },
  {
    id: "github-backup-week",
    title: "GitHub 备份周",
    category: "AI与技能",
    description: "整理和备份你的代码仓库，养成版本控制习惯。",
    suitableFor: ["代码没有备份习惯", "仓库结构混乱", "想学习 Git 工作流"],
    weeklyGoal: "所有项目完成 Git 初始化并推送到 GitHub",
    dailyAction: "每天选择一个项目进行整理、提交和推送",
    minimumStandard: "每天至少提交一次代码",
    checkInType: "次数",
    reviewQuestions: ["Git 操作熟练度有提升吗？", "仓库结构整理得怎么样？", "以后怎么保持提交习惯？"],
    tags: ["Git", "GitHub", "备份"],
    icon: "GitBranch",
    color: "#1F2937",
  },
  {
    id: "software-polish-week",
    title: "个人软件优化周",
    category: "AI与技能",
    description: "对自己正在开发或使用的软件进行优化和改进。",
    suitableFor: ["有个人项目但不够完善", "想提升代码质量", "想增加功能或修复 bug"],
    weeklyGoal: "完成 5 个优化点或修复 10 个 bug",
    dailyAction: "每天选一个问题进行修复或优化，记录变更",
    minimumStandard: "每天至少处理一个优化项",
    checkInType: "个数",
    reviewQuestions: ["哪些优化效果最明显？", "代码质量有提升吗？", "下个版本最想加什么功能？"],
    tags: ["开发", "优化", "代码"],
    icon: "Wrench",
    color: "#374151",
  },
  {
    id: "automation-week",
    title: "自动化周",
    category: "AI与技能",
    description: "发现生活中的重复任务，用工具和脚本实现自动化。",
    suitableFor: ["每天做很多重复性工作", "想提高效率减少手动操作", "对自动化感兴趣"],
    weeklyGoal: "实现 3 个日常任务的自动化",
    dailyAction: "每天找一个可自动化的场景，用工具或脚本实现",
    minimumStandard: "每周至少完成 1 个自动化方案",
    checkInType: "个数",
    reviewQuestions: ["哪个自动化方案最省时间？", "实施过程中遇到什么困难？", "下周想自动化什么？"],
    tags: ["自动化", "效率", "工具"],
    icon: "Zap",
    color: "#F59E0B",
  },
  // ═══════════════════════════════════════════════════════════
  // 健康运动
  // ═══════════════════════════════════════════════════════════
  {
    id: "exercise-week",
    title: "运动周",
    category: "健康运动",
    description: "每天安排一定量的运动，让身体动起来，提升精力和心情。",
    suitableFor: ["长期坐着不动", "想养成运动习惯", "精力不足、容易累"],
    weeklyGoal: "完成 5 次运动，每次 30 分钟以上",
    dailyAction: "每天做一项运动（跑步/跳绳/健身/球类），记录完成情况",
    minimumStandard: "每天至少运动 10 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["哪种运动最让你感到愉悦？", "运动后精力状态有变化吗？", "下周想尝试什么新运动？"],
    tags: ["运动", "健康", "活力"],
    icon: "Activity",
    color: "#10B981",
  },
  {
    id: "walking-week",
    title: "散步周",
    category: "健康运动",
    description: "每天出门散步，用最轻松的方式让自己动起来。",
    suitableFor: ["不想剧烈运动", "想出门但缺乏动力", "想放松心情"],
    weeklyGoal: "散步 7 天，每天至少 20 分钟",
    dailyAction: "每天出门散步 20-30 分钟，不戴耳机感受周围",
    minimumStandard: "每天至少散步 10 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["散步的时候在想什么？", "有没有发现平时忽略的风景？", "散步后心情有什么变化？"],
    tags: ["散步", "轻松", "户外"],
    icon: "Footprints",
    color: "#34D399",
  },
  {
    id: "stretching-week",
    title: "拉伸周",
    category: "健康运动",
    description: "每天做拉伸和放松练习，缓解肌肉紧张，改善体态。",
    suitableFor: ["久坐导致肩颈酸痛", "身体僵硬不灵活", "想改善体态"],
    weeklyGoal: "连续 7 天拉伸，每次 15 分钟以上",
    dailyAction: "每天做 15 分钟全身拉伸，重点关注肩颈和腰部",
    minimumStandard: "每天至少拉伸 5 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["拉伸后身体感觉有什么变化？", "哪个部位的拉伸最舒服？", "以后会继续保持拉伸习惯吗？"],
    tags: ["拉伸", "放松", "体态"],
    icon: "Accessibility",
    color: "#6EE7B7",
  },
  {
    id: "park-week",
    title: "公园周",
    category: "健康运动",
    description: "每天去公园待一会儿，接触自然，放松身心。",
    suitableFor: ["整天待在室内", "想接触大自然", "需要放松和换环境"],
    weeklyGoal: "去 5 次不同的公园或在同一个公园认真逛",
    dailyAction: "每天去公园散步/坐一会儿/看书，至少 20 分钟",
    minimumStandard: "每周至少去 3 次公园",
    checkInType: "次数",
    reviewQuestions: ["在公园里做什么最放松？", "哪个公园最让你喜欢？", "接触自然对你的心情有什么影响？"],
    tags: ["户外", "自然", "放松"],
    icon: "TreePine",
    color: "#22C55E",
  },
  {
    id: "sunshine-week",
    title: "晒太阳周",
    category: "健康运动",
    description: "每天保证一定的日照时间，补充维生素D，提升心情。",
    suitableFor: ["整天在室内不见阳光", "情绪容易低落", "想改善睡眠质量"],
    weeklyGoal: "晒太阳累计 3.5 小时以上",
    dailyAction: "每天在户外晒 15-30 分钟太阳（避开正午暴晒）",
    minimumStandard: "每天至少晒 10 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["晒太阳后心情有变化吗？", "睡眠质量有改善吗？", "什么时间段晒太阳最舒服？"],
    tags: ["健康", "阳光", "心情"],
    icon: "Sun",
    color: "#FBBF24",
  },
  {
    id: "posture-week",
    title: "体态改善周",
    category: "健康运动",
    description: "关注日常体态，纠正不良姿势，让身体更挺拔健康。",
    suitableFor: ["驼背圆肩", "长期看手机脖子前倾", "想提升气质"],
    weeklyGoal: "掌握 3 个体态纠正动作，日常保持正确姿势",
    dailyAction: "每小时检查一次体态，做 2 分钟纠正练习",
    minimumStandard: "每天至少做 3 次体态检查",
    checkInType: "次数",
    reviewQuestions: ["哪个体态问题改善最明显？", "保持正确姿势的难点在哪里？", "以后怎么维持好体态？"],
    tags: ["体态", "纠正", "健康"],
    icon: "Heart",
    color: "#F43F5E",
  },
  {
    id: "sedentary-rescue-week",
    title: "久坐拯救周",
    category: "健康运动",
    description: "打破久坐习惯，每隔一段时间站起来活动。",
    suitableFor: ["一天坐 8 小时以上", "腰背经常不舒服", "想培养活动习惯"],
    weeklyGoal: "每 45 分钟站起来活动一次，每天累计活动 1 小时",
    dailyAction: "设置番茄钟，每 45 分钟起来活动 5 分钟",
    minimumStandard: "每小时至少起来一次",
    checkInType: "次数",
    reviewQuestions: ["打破久坐后身体有什么变化？", "最难坚持的是什么时候？", "以后会继续保持这个习惯吗？"],
    tags: ["久坐", "活动", "健康"],
    icon: "Timer",
    color: "#E11D48",
  },
  {
    id: "after-dinner-walk-week",
    title: "饭后散步周",
    category: "健康运动",
    description: "养成饭后散步的习惯，帮助消化，防止积食。",
    suitableFor: ["饭后马上坐下/躺下", "消化不好", "想增加日常活动量"],
    weeklyGoal: "7 天坚持饭后散步 10-15 分钟",
    dailyAction: "每顿饭后散步 10-15 分钟（至少保证晚餐后）",
    minimumStandard: "每天至少散步一次",
    checkInType: "次数",
    reviewQuestions: ["饭后散步对消化有帮助吗？", "什么时候散步最舒服？", "这个习惯能坚持多久？"],
    tags: ["散步", "消化", "习惯"],
    icon: "Utensils",
    color: "#F97316",
  },
  // ═══════════════════════════════════════════════════════════
  // 养生作息
  // ═══════════════════════════════════════════════════════════
  {
    id: "early-sleep-week",
    title: "早睡周",
    category: "养生作息",
    description: "每天在目标时间前上床睡觉，改善睡眠质量和作息规律。",
    suitableFor: ["经常熬夜", "睡眠不足", "想调整作息但做不到"],
    weeklyGoal: "连续 7 天在 23:00 前上床睡觉",
    dailyAction: "睡前 1 小时放下手机，看书或冥想，23:00 前熄灯",
    minimumStandard: "每天在 23:30 前上床",
    checkInType: "达标/未达标",
    reviewQuestions: ["早睡后白天的精神状态有变化吗？", "最难熬的是睡前不玩手机吗？", "下周想几点睡？"],
    tags: ["早睡", "睡眠", "作息"],
    icon: "Moon",
    color: "#1E3A5F",
  },
  {
    id: "early-rise-week",
    title: "早起周",
    category: "养生作息",
    description: "坚持每天早起，利用早晨的高效时间做重要的事。",
    suitableFor: ["早上起不来", "总觉得一天时间不够用", "想拥有更多可控时间"],
    weeklyGoal: "连续 7 天在 7:00 前起床",
    dailyAction: "起床后做 10 分钟晨间仪式（喝水/拉伸/计划当天）",
    minimumStandard: "每天在 7:30 前起床",
    checkInType: "达标/未达标",
    reviewQuestions: ["早起后感觉一天变长了吗？", "早上这段时间做了什么最有意义的事？", "早起的动力来源是什么？"],
    tags: ["早起", "作息", "效率"],
    icon: "Sunrise",
    color: "#F97316",
  },
  {
    id: "less-late-night-week",
    title: "少熬夜周",
    category: "养生作息",
    description: "减少熬夜次数，逐步把作息调回正轨。",
    suitableFor: ["经常熬夜到凌晨", "想减少熬夜但控制不住", "熬夜后第二天状态很差"],
    weeklyGoal: "本周熬夜不超过 2 次（凌晨 0:00 后睡算熬夜）",
    dailyAction: "22:00 开始准备睡觉，设置手机自动关机/开启勿扰",
    minimumStandard: "每周熬夜不超过 3 次",
    checkInType: "达标/未达标",
    reviewQuestions: ["什么原因最容易导致熬夜？", "怎么抵抗「再看一集/再玩一局」的冲动？", "少熬夜后身体状态有改善吗？"],
    tags: ["熬夜", "作息", "改善"],
    icon: "BedDouble",
    color: "#4B5563",
  },
  {
    id: "bedtime-relax-week",
    title: "睡前放松周",
    category: "养生作息",
    description: "建立睡前放松仪式，帮助身心过渡到睡眠状态。",
    suitableFor: ["躺下睡不着", "睡前脑子还在工作", "睡眠质量差"],
    weeklyGoal: "每晚执行睡前放松仪式，入睡时间缩短到 15 分钟内",
    dailyAction: "睡前 30 分钟做放松活动（温水泡脚/冥想/轻柔拉伸/听白噪音）",
    minimumStandard: "每天至少做 10 分钟睡前放松",
    checkInType: "时长(分钟)",
    reviewQuestions: ["哪种放松方式最助眠？", "做放松仪式和直接睡差别大吗？", "会把这个习惯保持下去吗？"],
    tags: ["睡眠", "放松", "仪式"],
    icon: "Flower2",
    color: "#A855F7",
  },
  {
    id: "drink-water-week",
    title: "喝水周",
    category: "养生作息",
    description: "保证每天充足饮水，养成主动喝水的习惯。",
    suitableFor: ["一天不喝水也不觉得渴", "经常忘记喝水", "想改善皮肤状态"],
    weeklyGoal: "每天喝 2L 水（约 8 杯），连续 7 天",
    dailyAction: "床头/桌边放水杯，每小时喝一杯，用 App 或手环提醒",
    minimumStandard: "每天至少喝 1.5L",
    checkInType: "水量(L)",
    reviewQuestions: ["喝够水的日子身体感觉有什么不同？", "什么时候最容易忘记喝水？", "以后怎么维持这个习惯？"],
    tags: ["喝水", "健康", "习惯"],
    icon: "Droplets",
    color: "#3B82F6",
  },
  {
    id: "breakfast-week",
    title: "早餐周",
    category: "养生作息",
    description: "坚持每天吃早餐，为一整天提供能量。",
    suitableFor: ["经常不吃早餐", "早餐随便对付", "想培养健康饮食习惯"],
    weeklyGoal: "连续 7 天吃营养早餐",
    dailyAction: "每天花 15 分钟准备和享用早餐，包含蛋白质+碳水+蔬果",
    minimumStandard: "每天至少吃早餐（种类不限）",
    checkInType: "达标/未达标",
    reviewQuestions: ["吃早餐后上午的精神状态有变化吗？", "最喜欢的早餐搭配是什么？", "以后会坚持吃早餐吗？"],
    tags: ["早餐", "饮食", "健康"],
    icon: "CupSoda",
    color: "#F59E0B",
  },
  {
    id: "cooking-week",
    title: "做饭周",
    category: "养生作息",
    description: "自己动手做饭，吃得更健康，也享受烹饪的乐趣。",
    suitableFor: ["天天点外卖", "想吃得健康但不会做", "想学做饭"],
    weeklyGoal: "自己做饭 5 次以上，学会 3 道新菜",
    dailyAction: "每天做一顿饭（早/午/晚均可），拍照记录",
    minimumStandard: "每周至少做 3 次饭",
    checkInType: "次数",
    reviewQuestions: ["自己做的最满意的一道菜是什么？", "做饭和点外卖的心情有什么不同？", "以后每周做几次饭？"],
    tags: ["做饭", "饮食", "生活技能"],
    icon: "ChefHat",
    color: "#EF4444",
  },
  {
    id: "eye-care-week",
    title: "护眼周",
    category: "养生作息",
    description: "减少屏幕时间，做眼保健操，保护视力。",
    suitableFor: ["每天看屏幕超过 8 小时", "眼睛干涩疲劳", "视力下降"],
    weeklyGoal: "每 30 分钟休息眼睛一次，每天做 2 次眼保健操",
    dailyAction: "设置定时器每 30 分钟看远处 1 分钟，早晚做眼保健操",
    minimumStandard: "每小时至少让眼睛休息一次",
    checkInType: "次数",
    reviewQuestions: ["眼睛疲劳感有减轻吗？", "最难坚持的是什么？", "以后怎么保护眼睛？"],
    tags: ["护眼", "健康", "屏幕"],
    icon: "Eye",
    color: "#0EA5E9",
  },
  // ═══════════════════════════════════════════════════════════
  // 情绪疗愈
  // ═══════════════════════════════════════════════════════════
  {
    id: "emotion-observation-week",
    title: "情绪观察周",
    category: "情绪疗愈",
    description: "每天观察和记录自己的情绪，了解情绪来源，学会与情绪相处。",
    suitableFor: ["情绪波动大", "经常莫名其妙心情不好", "想更好地了解自己"],
    weeklyGoal: "完成 7 天的情绪日记，识别 3 个情绪触发模式",
    dailyAction: "每天记录 3 次情绪状态（什么情绪+触发事件+身体感受）",
    minimumStandard: "每天至少记录 1 次情绪",
    checkInType: "次数",
    reviewQuestions: ["你最常见的情绪是什么？", "发现了哪些情绪触发模式？", "观察情绪本身有没有让你感觉好一些？"],
    tags: ["情绪", "觉察", "成长"],
    icon: "HeartHandshake",
    color: "#F43F5E",
  },
  {
    id: "journal-week",
    title: "日记周",
    category: "情绪疗愈",
    description: "每天写日记，梳理思绪，记录生活，与自己对话。",
    suitableFor: ["脑子里事情太多理不清", "想记录生活但坚持不了", "想通过写作整理思绪"],
    weeklyGoal: "连续写 7 天日记",
    dailyAction: "每天写 10 分钟日记，记录今天发生的事和感受",
    minimumStandard: "每天至少写 3 句话",
    checkInType: "字数",
    reviewQuestions: ["写日记后心理状态有什么变化？", "最喜欢写的日记内容是什么？", "以后会继续写日记吗？"],
    tags: ["日记", "表达", "梳理"],
    icon: "Book",
    color: "#EC4899",
  },
  {
    id: "slow-down-week",
    title: "慢下来周",
    category: "情绪疗愈",
    description: "刻意放慢生活节奏，减少 multitasking，专注当下。",
    suitableFor: ["每天都感觉很赶", "吃饭看手机走路听播客", "很久没有真正放松过"],
    weeklyGoal: "每天有 30 分钟完全放空的时间",
    dailyAction: "选一个日常活动放慢来做（慢慢吃饭/慢慢走路/慢慢喝茶）",
    minimumStandard: "每天至少有 10 分钟「慢」的时间",
    checkInType: "时长(分钟)",
    reviewQuestions: ["慢下来的时候是什么感觉？", "平常为什么总是那么赶？", "以后怎么在快节奏中留出慢时间？"],
    tags: ["慢生活", "放松", "当下"],
    icon: "Clock",
    color: "#8B5CF6",
  },
  {
    id: "less-anxiety-week",
    title: "少焦虑周",
    category: "情绪疗愈",
    description: "识别焦虑源头，用具体行动代替过度担忧，减少内耗。",
    suitableFor: ["经常为没发生的事焦虑", "容易陷入过度思考", "想减少精神内耗"],
    weeklyGoal: "每天做一次焦虑拆解练习，减少无效担忧时间",
    dailyAction: "当感到焦虑时写下焦虑的事，区分「能控制的」和「不能控制的」",
    minimumStandard: "每天至少做一次焦虑记录",
    checkInType: "次数",
    reviewQuestions: ["这周的焦虑主要来源是什么？", "哪些焦虑其实是没必要担心的？", "发现哪些方法能有效缓解焦虑？"],
    tags: ["焦虑", "内耗", "成长"],
    icon: "Brain",
    color: "#A855F7",
  },
  {
    id: "self-affirmation-week",
    title: "自我肯定周",
    category: "情绪疗愈",
    description: "每天对自己说一句肯定的话，建立积极的自我对话习惯。",
    suitableFor: ["经常自我批评", "自信不足", "容易否定自己"],
    weeklyGoal: "写出 10 条属于自己的肯定语句，每天重复",
    dailyAction: "早上对着镜子说一句肯定的话，晚上记录一件今天做得好的事",
    minimumStandard: "每天至少做一次自我肯定",
    checkInType: "达标/未达标",
    reviewQuestions: ["对自己说肯定的话时是什么感觉？", "自我对话的方式有变化吗？", "自信心有提升吗？"],
    tags: ["自我肯定", "自信", "积极"],
    icon: "Sparkles",
    color: "#D946EF",
  },
  {
    id: "relaxation-week",
    title: "放松周",
    category: "情绪疗愈",
    description: "做真正能让自己放松的事，恢复身心能量。",
    suitableFor: ["一直处于紧绷状态", "不知道怎么放松", "身心俱疲"],
    weeklyGoal: "每天安排 1 小时的专属放松时间",
    dailyAction: "每天做一件让自己真正放松的事（泡澡/听音乐/发呆/按摩/瑜伽）",
    minimumStandard: "每天至少放松 20 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["做什么事最让你放松？", "放松后的身心状态有什么变化？", "以后每周留多少时间给自己放松？"],
    tags: ["放松", "恢复", "自我照顾"],
    icon: "Coffee",
    color: "#F59E0B",
  },
  {
    id: "no-burnout-week",
    title: "不内耗周",
    category: "情绪疗愈",
    description: "停止过度思考和自我消耗，学会放过自己。",
    suitableFor: ["容易想太多", "总在纠结过去的选择", "过度在意别人看法"],
    weeklyGoal: "识别并减少 3 种内耗模式，每天内耗时间减少 50%",
    dailyAction: "当意识到在内耗时，对自己说「停下来」，立即转移注意力做别的事",
    minimumStandard: "每天至少识别一次内耗",
    checkInType: "次数",
    reviewQuestions: ["这周识别出哪些内耗模式？", "用什么方法成功打断了内耗？", "不内耗的日子感觉怎么样？"],
    tags: ["内耗", "停止", "自在"],
    icon: "Wind",
    color: "#06B6D4",
  },
  {
    id: "brain-dump-week",
    title: "清空大脑周",
    category: "情绪疗愈",
    description: "把所有想法从脑子里倒出来，减轻心理负担。",
    suitableFor: ["脑子里事情太多", "睡不着时一直在想事", "感觉信息过载"],
    weeklyGoal: "完成 7 次大脑清空练习",
    dailyAction: "每天花 10 分钟把脑子里的想法全部写下来（不分类不整理）",
    minimumStandard: "每天至少写 5 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["把想法写出来后的心理感受如何？", "一周后回头看写了什么？", "以后怎么保持大脑清爽？"],
    tags: ["清理", "减压", "思绪"],
    icon: "Trash2",
    color: "#64748B",
  },
  // ═══════════════════════════════════════════════════════════
  // 生活整理
  // ═══════════════════════════════════════════════════════════
  {
    id: "room-organization-week",
    title: "房间整理周",
    category: "生活整理",
    description: "彻底整理房间，创造清爽舒适的居住空间。",
    suitableFor: ["房间乱糟糟", "找不到东西", "想改善生活环境"],
    weeklyGoal: "房间完成彻底整理，每个区域都有固定收纳位置",
    dailyAction: "每天整理一个区域（书桌/衣柜/床底/阳台/厨房等）",
    minimumStandard: "每天至少整理 15 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["整理完最大的感受是什么？", "哪个区域整理前后变化最大？", "以后怎么保持房间整洁？"],
    tags: ["整理", "房间", "生活"],
    icon: "Home",
    color: "#6366F1",
  },
  {
    id: "desk-cleanup-week",
    title: "书桌清理周",
    category: "生活整理",
    description: "整理书桌和学习/工作区域，打造高效舒适的工作空间。",
    suitableFor: ["书桌堆满杂物", "在杂乱的环境中效率低", "想有更好的学习工作空间"],
    weeklyGoal: "完成书桌彻底整理，建立桌面物品归位体系",
    dailyAction: "每天清理桌面，只留当下需要的物品，用完归位",
    minimumStandard: "每天至少保持桌面整洁",
    checkInType: "达标/未达标",
    reviewQuestions: ["书桌整洁后工作效率有变化吗？", "哪些物品其实根本不需要放在桌上？", "以后怎么维持桌面整洁？"],
    tags: ["书桌", "整理", "效率"],
    icon: "Monitor",
    color: "#4F46E5",
  },
  {
    id: "wardrobe-week",
    title: "衣柜整理周",
    category: "生活整理",
    description: "整理衣柜，断舍离不穿的衣物，让穿搭更轻松。",
    suitableFor: ["衣柜塞得满满的却总觉得没衣服穿", "想减少选择困难", "换季需要整理"],
    weeklyGoal: "完成衣柜彻底整理，淘汰 10 件以上不穿的衣物",
    dailyAction: "每天整理一个衣柜区域，试穿并决定去留",
    minimumStandard: "每天至少处理 5 件衣服",
    checkInType: "件数",
    reviewQuestions: ["淘汰衣服时的心态是什么样的？", "整理完搭配衣服更容易了吗？", "以后还会乱买衣服吗？"],
    tags: ["衣柜", "整理", "断舍离"],
    icon: "Shirt",
    color: "#8B5CF6",
  },
  {
    id: "declutter-week",
    title: "断舍离周",
    category: "生活整理",
    description: "用「断舍离」的方式清理物品和生活，只留下真正需要的。",
    suitableFor: ["东西越来越多", "不舍得扔东西", "想过极简生活"],
    weeklyGoal: "清理 30 件以上不再需要的物品",
    dailyAction: "每天选一个区域/类别清理 5 件以上物品（扔掉/捐赠/卖掉）",
    minimumStandard: "每天至少清理 3 件物品",
    checkInType: "件数",
    reviewQuestions: ["断舍离的过程中你有什么感悟？", "最难舍弃的是什么？", "清理之后生活空间有什么变化？"],
    tags: ["断舍离", "极简", "清理"],
    icon: "PackageOpen",
    color: "#A78BFA",
  },
  {
    id: "rental-optimization-week",
    title: "租房优化周",
    category: "生活整理",
    description: "优化租房空间，用低成本的方式让居住环境更舒适。",
    suitableFor: ["租的房子住得不舒服", "想改造居住环境但预算有限", "搬家后需要整理"],
    weeklyGoal: "完成 3 个房间优化方案（收纳/布置/整洁）",
    dailyAction: "每天完成一个房间优化任务（添置收纳/调整布局/深度清洁）",
    minimumStandard: "每周至少完成 2 个优化项目",
    checkInType: "个数",
    reviewQuestions: ["哪个优化方案最让居住体验提升？", "花了多少钱？性价比高吗？", "下一个想优化什么？"],
    tags: ["租房", "改造", "生活品质"],
    icon: "Building2",
    color: "#7C3AED",
  },
  {
    id: "cleaning-week",
    title: "卫生周",
    category: "生活整理",
    description: "进行全屋深度清洁，消灭卫生死角。",
    suitableFor: ["很久没有大扫除", "卫生状况需要改善", "想住得更干净舒适"],
    weeklyGoal: "完成全屋深度清洁",
    dailyAction: "每天清洁一个区域（厨房/卫生间/卧室/客厅/阳台等）",
    minimumStandard: "每天至少清洁 20 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["大扫除后居住感受有什么不同？", "哪里的卫生最容易被忽略？", "以后怎么保持家里干净？"],
    tags: ["清洁", "卫生", "整理"],
    icon: "SprayCan",
    color: "#0EA5E9",
  },
  {
    id: "phone-cleanup-week",
    title: "手机清理周",
    category: "生活整理",
    description: "清理手机里的无用文件和应用，减少数字混乱。",
    suitableFor: ["手机内存不够", "桌面图标乱糟糟", "收到大量垃圾通知"],
    weeklyGoal: "清理出 5GB 以上空间，桌面 app 精简到 2 页以内",
    dailyAction: "每天清理一个类别（照片/视频/app/文件/缓存）",
    minimumStandard: "每天至少清理 5 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["清理出多少空间？", "关闭通知后手机使用时间有减少吗？", "以后怎么保持手机整洁？"],
    tags: ["手机", "清理", "数字整理"],
    icon: "Smartphone",
    color: "#22C55E",
  },
  {
    id: "computer-cleanup-week",
    title: "电脑清理周",
    category: "生活整理",
    description: "整理电脑文件和桌面，清理无用软件，提升工作效率。",
    suitableFor: ["电脑桌面堆满文件", "C 盘快满了", "软件装了一大堆用不上的"],
    weeklyGoal: "清理出 10GB 以上空间，桌面文件归类整理完毕",
    dailyAction: "每天清理一个区域（桌面/下载/文档/软件/浏览器书签）",
    minimumStandard: "每天至少整理 10 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["电脑清理后运行速度有变化吗？", "哪些文件最占空间？", "以后怎么保持文件整洁？"],
    tags: ["电脑", "整理", "效率"],
    icon: "Laptop",
    color: "#2563EB",
  },
  // ═══════════════════════════════════════════════════════════
  // 兴趣探索
  // ═══════════════════════════════════════════════════════════
  {
    id: "handcraft-week",
    title: "手工周",
    category: "兴趣探索",
    description: "动手做手工，培养创造力，获得成就感和心流体验。",
    suitableFor: ["整天对着屏幕", "想动手做点什么", "寻找新的兴趣爱好"],
    weeklyGoal: "完成 2 个手工作品",
    dailyAction: "每天花 30 分钟做手工（折纸/编织/拼图/黏土/木工等）",
    minimumStandard: "每天至少做 15 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["做手工时是什么状态和心情？", "对自己的作品满意吗？", "以后会继续做手工吗？"],
    tags: ["手工", "创造", "专注"],
    icon: "Paintbrush",
    color: "#EC4899",
  },
  {
    id: "photography-week",
    title: "拍照周",
    category: "兴趣探索",
    description: "每天拍一张好照片，用镜头观察生活，发现日常之美。",
    suitableFor: ["想学拍照但没行动", "生活很单调想换个视角", "想记录生活"],
    weeklyGoal: "拍 7 张自己满意的照片，学习 3 个摄影技巧",
    dailyAction: "每天拍至少一张照片，选题不限（风景/人物/街拍/静物）",
    minimumStandard: "每天至少拍一张",
    checkInType: "张数",
    reviewQuestions: ["这周拍的最喜欢的一张照片是哪个？", "拍照过程中发现了什么平时忽略的美？", "摄影水平有提升吗？"],
    tags: ["摄影", "创作", "生活"],
    icon: "Camera",
    color: "#06B6D4",
  },
  {
    id: "cafe-week",
    title: "咖啡馆周",
    category: "兴趣探索",
    description: "探索不同的咖啡馆，在不一样的环境中学习或发呆。",
    suitableFor: ["想换换学习工作环境", "喜欢咖啡馆的氛围", "想探索城市"],
    weeklyGoal: "打卡 4 家不同的咖啡馆",
    dailyAction: "每天去一家不同的咖啡馆，待至少 1 小时",
    minimumStandard: "每周至少去 2 家咖啡馆",
    checkInType: "次数",
    reviewQuestions: ["哪家咖啡馆最值得推荐？", "在不同咖啡馆的效率有什么不同？", "最喜欢什么风格的咖啡馆？"],
    tags: ["咖啡馆", "探索", "生活"],
    icon: "Mug",
    color: "#D97706",
  },
  {
    id: "food-exploration-week",
    title: "美食探索周",
    category: "兴趣探索",
    description: "尝试新的食物和餐厅，拓展味蕾经验。",
    suitableFor: ["每天吃同样的东西", "想发现新的美食", "生活缺少新鲜感"],
    weeklyGoal: "尝试 5 种新食物/餐厅，找到 2 个会再去的店",
    dailyAction: "每天尝试一种没吃过的东西或去一家新店",
    minimumStandard: "每周至少尝试 3 种新食物",
    checkInType: "次数",
    reviewQuestions: ["本周最佳发现是什么？", "有没有踩雷的？", "以后会继续保持探索新食物的习惯吗？"],
    tags: ["美食", "探索", "生活"],
    icon: "UtensilsCrossed",
    color: "#EF4444",
  },
  {
    id: "drawing-week",
    title: "画画周",
    category: "兴趣探索",
    description: "每天画点什么，释放创造力，不用画得很好，享受过程就好。",
    suitableFor: ["觉得自己不会画画", "想用画画表达情绪", "想尝试创意活动"],
    weeklyGoal: "完成 5 幅画/涂鸦",
    dailyAction: "每天花 20 分钟画画（速写/涂鸦/水彩/数字绘画均可）",
    minimumStandard: "每天至少画 10 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["画画过程中是什么感受？", "对自己的画满意吗？", "画画对你来说意味着什么？"],
    tags: ["画画", "创作", "表达"],
    icon: "Palette",
    color: "#D946EF",
  },
  {
    id: "music-week",
    title: "音乐周",
    category: "兴趣探索",
    description: "每天听不同类型的音乐，或者学习一首新曲子。",
    suitableFor: ["喜欢音乐但很少主动听", "想拓宽音乐品味", "想学乐器"],
    weeklyGoal: "建立一份新的歌单，或学会弹一首曲子",
    dailyAction: "每天听一张新专辑/一种新风格，或练习乐器 20 分钟",
    minimumStandard: "每天至少听 15 分钟音乐",
    checkInType: "时长(分钟)",
    reviewQuestions: ["这周发现了什么好音乐？", "哪种音乐风格最打动你？", "音乐对你的情绪有什么影响？"],
    tags: ["音乐", "探索", "艺术"],
    icon: "Music",
    color: "#8B5CF6",
  },
  {
    id: "movie-week",
    title: "电影周",
    category: "兴趣探索",
    description: "每天看一部电影（或分几天看完），拓展视野和感受。",
    suitableFor: ["很久没有好好看电影", "想通过电影学习/感受", "想丰富精神生活"],
    weeklyGoal: "看完 3 部电影，每篇写 100 字短评",
    dailyAction: "每天看一部电影或分两天看完一部，看完写几句话感受",
    minimumStandard: "每周至少看 2 部电影",
    checkInType: "部数",
    reviewQuestions: ["这周最喜欢哪部电影？", "电影带给你什么思考？", "以后想多看看什么类型的电影？"],
    tags: ["电影", "文化", "思考"],
    icon: "Clapperboard",
    color: "#6366F1",
  },
  {
    id: "journaling-week",
    title: "手账周",
    category: "兴趣探索",
    description: "每天做手账记录，把生活变成美丽的视觉日记。",
    suitableFor: ["喜欢文具和贴纸", "想更有仪式感地记录生活", "想培养创意习惯"],
    weeklyGoal: "完成 7 页手账",
    dailyAction: "每天花 20-30 分钟做手账，可以画/贴/写",
    minimumStandard: "每天至少做一页",
    checkInType: "页数",
    reviewQuestions: ["做手账时是什么心情？", "最喜欢哪一页的设计？", "以后会继续做手账吗？"],
    tags: ["手账", "记录", "创意"],
    icon: "NotebookPen",
    color: "#A855F7",
  },
  // ═══════════════════════════════════════════════════════════
  // 社交关系
  // ═══════════════════════════════════════════════════════════
  {
    id: "connect-friends-week",
    title: "联系朋友周",
    category: "社交关系",
    description: "主动联系久未联系的朋友，维护和修复人际关系。",
    suitableFor: ["很久没联系朋友了", "社交圈越来越小", "想增进和朋友的关系"],
    weeklyGoal: "主动联系 5 位朋友，与 1 位朋友深入聊一次",
    dailyAction: "每天给一位朋友发消息/打电话，问问近况",
    minimumStandard: "每周至少联系 3 位朋友",
    checkInType: "次数",
    reviewQuestions: ["联系朋友时他们的反应怎么样？", "哪次聊天让你最开心？", "以后怎么保持和朋友的联系？"],
    tags: ["朋友", "社交", "关系"],
    icon: "Users",
    color: "#3B82F6",
  },
  {
    id: "family-week",
    title: "家人沟通周",
    category: "社交关系",
    description: "主动与家人沟通，表达关心，增进家庭关系。",
    suitableFor: ["好久没给家人打电话", "和家人关系有些疏远", "想改善家庭沟通"],
    weeklyGoal: "与家人深度沟通 2 次以上",
    dailyAction: "每天给家人发一条问候消息，或分享一件今天发生的小事",
    minimumStandard: "每周至少与家人视频/电话 2 次",
    checkInType: "次数",
    reviewQuestions: ["家人对你主动联系有什么反应？", "沟通中有没有意外收获？", "以后怎么保持和家人沟通的频率？"],
    tags: ["家人", "沟通", "亲情"],
    icon: "Heart",
    color: "#F43F5E",
  },
  {
    id: "date-week",
    title: "约会周",
    category: "社交关系",
    description: "为伴侣或喜欢的人安排特别的约会，创造美好回忆。",
    suitableFor: ["恋爱进入平淡期", "想给对方惊喜", "想增进感情"],
    weeklyGoal: "安排 2 次有质量的约会",
    dailyAction: "每天做一件让伴侣感到被爱的小事（写纸条/准备早餐/按摩等）",
    minimumStandard: "每周至少安排 1 次特别约会",
    checkInType: "次数",
    reviewQuestions: ["对方最喜欢什么安排？", "这周感情有什么变化？", "下次约会想做什么？"],
    tags: ["恋爱", "约会", "浪漫"],
    icon: "Heart",
    color: "#EC4899",
  },
  {
    id: "gratitude-week",
    title: "表达感谢周",
    category: "社交关系",
    description: "主动向身边的人表达感谢，培养感恩心态。",
    suitableFor: ["很少表达感谢", "觉得别人的付出是理所当然", "想变得更积极"],
    weeklyGoal: "向 7 个不同的人表达感谢",
    dailyAction: "每天找一个人，真诚地对 TA 说一句谢谢",
    minimumStandard: "每天至少感谢一个人",
    checkInType: "次数",
    reviewQuestions: ["表达感谢时对方的反应怎么样？", "表达感谢后你自己的心情如何？", "以后怎么保持感恩的习惯？"],
    tags: ["感恩", "表达", "积极"],
    icon: "ThumbsUp",
    color: "#F59E0B",
  },
  {
    id: "social-courage-week",
    title: "社交勇气周",
    category: "社交关系",
    description: "挑战自己做一些需要社交勇气的「社牛」小事。",
    suitableFor: ["社交恐惧", "想突破舒适圈", "想变得更自信"],
    weeklyGoal: "完成 5 个社交勇气挑战",
    dailyAction: "每天做一件需要社交勇气的事（主动搭话/问路/在群里发言/赞美陌生人）",
    minimumStandard: "每周至少完成 3 个挑战",
    checkInType: "次数",
    reviewQuestions: ["哪个挑战最难？完成后的感受如何？", "发现自己的社交舒适圈有多大？", "社交勇气有增长吗？"],
    tags: ["社交", "勇气", "挑战"],
    icon: "Zap",
    color: "#F97316",
  },
  {
    id: "compliment-week",
    title: "夸夸别人周",
    category: "社交关系",
    description: "每天真心地赞美一个人，让周围充满正能量。",
    suitableFor: ["习惯性挑剔", "想给别人带来快乐", "想改善人际关系"],
    weeklyGoal: "真心赞美 7 个不同的人",
    dailyAction: "每天找一个值得赞美的人，真诚地表达赞美",
    minimumStandard: "每天至少赞美一个人",
    checkInType: "次数",
    reviewQuestions: ["赞美别人时对方是什么反应？", "赞美别人时你自己的感受如何？", "发现赞美能给关系带来什么变化？"],
    tags: ["赞美", "积极", "关系"],
    icon: "Star",
    color: "#EAB308",
  },
  {
    id: "listening-week",
    title: "倾听周",
    category: "社交关系",
    description: "在与他人交流时专注倾听，不打断、不评判。",
    suitableFor: ["总想打断别人", "不会倾听", "想提升沟通质量"],
    weeklyGoal: "进行 5 次高质量倾听对话",
    dailyAction: "每次对话时刻意练习倾听：不打断、有眼神交流、做回应",
    minimumStandard: "每天至少有一次专注倾听的对话",
    checkInType: "次数",
    reviewQuestions: ["专注倾听和平时听别人说话有什么不同？", "对方有什么反应？", "倾听给你的沟通带来了什么变化？"],
    tags: ["倾听", "沟通", "关系"],
    icon: "Ear",
    color: "#06B6D4",
  },
  {
    id: "intimacy-week",
    title: "亲密关系周",
    category: "社交关系",
    description: "专注经营亲密关系，增加连接感和理解。",
    suitableFor: ["和伴侣沟通变少", "感情有些疏远", "想增进亲密关系"],
    weeklyGoal: "与伴侣进行 3 次深度对话",
    dailyAction: "每天和伴侣分享一件今天发生的事和一个感受",
    minimumStandard: "每天至少和伴侣有 15 分钟不被打扰的交流",
    checkInType: "时长(分钟)",
    reviewQuestions: ["深度对话后感觉关系有什么变化？", "发现了对方哪些平时没注意到的想法？", "以后怎么保持高质量的交流？"],
    tags: ["亲密关系", "沟通", "感情"],
    icon: "Heart",
    color: "#E11D48",
  },
  // ═══════════════════════════════════════════════════════════
  // 工作实习
  // ═══════════════════════════════════════════════════════════
  {
    id: "intern-prep-week",
    title: "实习准备周",
    category: "工作实习",
    description: "系统准备实习申请，包括简历、作品集、面试准备。",
    suitableFor: ["即将申请实习", "简历需要更新", "不知道实习从哪里开始找"],
    weeklyGoal: "完成简历修改，投递 5 个实习岗位",
    dailyAction: "每天完成一个小任务（简历/求职信/搜索岗位/ networking）",
    minimumStandard: "每天至少花 30 分钟准备",
    checkInType: "时长(分钟)",
    reviewQuestions: ["简历优化后自己满意吗？", "投递后有收到回应吗？", "面试准备最需要加强的是什么？"],
    tags: ["实习", "求职", "简历"],
    icon: "Briefcase",
    color: "#3B82F6",
  },
  {
    id: "trade-study-week",
    title: "外贸学习周",
    category: "工作实习",
    description: "学习外贸基础知识和实务技能，为外贸行业做准备。",
    suitableFor: ["想进入外贸行业", "外贸专业学生", "想提升商务英语"],
    weeklyGoal: "掌握外贸基础知识框架和常用术语",
    dailyAction: "每天学习一个外贸模块（术语/流程/单证/物流/谈判）",
    minimumStandard: "每天至少学习 30 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["哪部分知识最有用？", "还有哪些方面需要深入了解？", "对外贸行业的信心有增加吗？"],
    tags: ["外贸", "学习", "职场"],
    icon: "Globe",
    color: "#06B6D4",
  },
  {
    id: "business-comm-week",
    title: "商务沟通周",
    category: "工作实习",
    description: "练习职场中的商务沟通，包括邮件、会议、汇报等场景。",
    suitableFor: ["职场沟通不够专业", "英文邮件写得不好", "害怕在会议上发言"],
    weeklyGoal: "掌握 5 种场景的商务沟通模板",
    dailyAction: "每天练习一个沟通场景（邮件/电话/会议/汇报/谈判）",
    minimumStandard: "每天至少练习 15 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["哪种沟通场景最需要提升？", "练习后实际沟通时有什么变化？", "商务沟通中最大的收获是什么？"],
    tags: ["商务", "沟通", "职场"],
    icon: "MessageSquare",
    color: "#2563EB",
  },
  {
    id: "resume-optimize-week",
    title: "简历优化周",
    category: "工作实习",
    description: "深入优化简历内容，让简历更吸引 HR 和面试官。",
    suitableFor: ["简历投了没回音", "不知道怎么写简历", "想针对不同岗位优化简历"],
    weeklyGoal: "完成 1 份高质量简历，针对 3 个目标岗位做定制化修改",
    dailyAction: "每天优化简历的一个模块（个人信息/教育/经历/技能/项目等）",
    minimumStandard: "每天至少花 20 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["简历优化后对比原来提升在哪里？", "目标岗位需要哪些关键技能？", "投递后收到回应的比例提高了吗？"],
    tags: ["简历", "求职", "职业"],
    icon: "FileText",
    color: "#8B5CF6",
  },
  {
    id: "interview-prep-week",
    title: "面试准备周",
    category: "工作实习",
    description: "系统准备面试，包括自我介绍、常见问题、模拟面试。",
    suitableFor: ["即将面试很紧张", "面试总是被刷", "想提升面试表现"],
    weeklyGoal: "准备 10 个高频面试问题的回答，完成 3 次模拟面试",
    dailyAction: "每天准备 2 个面试问题，录制回答并回看改进",
    minimumStandard: "每天至少练习 1 个面试问题",
    checkInType: "个数",
    reviewQuestions: ["自我介绍打磨后感觉怎么样？", "模拟面试发现什么问题？", "面试的自信心有提升吗？"],
    tags: ["面试", "求职", "准备"],
    icon: "Users",
    color: "#7C3AED",
  },
  {
    id: "career-explore-week",
    title: "职业探索周",
    category: "工作实习",
    description: "探索不同的职业方向，了解行业信息，明确职业规划。",
    suitableFor: ["不知道以后做什么", "对当前专业不满意", "想转行但不确定方向"],
    weeklyGoal: "深入了解 3 个职业方向，完成 1 次行业调研",
    dailyAction: "每天调研一个职业方向（看 JD/读面经/了解发展路径）",
    minimumStandard: "每天至少花 20 分钟了解职业信息",
    checkInType: "时长(分钟)",
    reviewQuestions: ["哪个职业方向最吸引你？", "了解到的信息和想象中一样吗？", "下一步的探索计划是什么？"],
    tags: ["职业", "探索", "规划"],
    icon: "Compass",
    color: "#F59E0B",
  },
  {
    id: "portfolio-week",
    title: "作品集周",
    category: "工作实习",
    description: "整理和优化个人作品集，展示自己的能力和项目经验。",
    suitableFor: ["没有作品集", "作品集需要更新", "想展示自己的项目成果"],
    weeklyGoal: "完成/更新作品集，添加 3 个项目案例",
    dailyAction: "每天打磨一个项目展示（背景/过程/成果/技术亮点）",
    minimumStandard: "每天至少完善一个项目",
    checkInType: "个数",
    reviewQuestions: ["作品集完成后满意度如何？", "哪些项目最能体现你的能力？", "作品集对求职有帮助吗？"],
    tags: ["作品集", "求职", "展示"],
    icon: "FolderOpen",
    color: "#6366F1",
  },
  {
    id: "email-express-week",
    title: "邮件表达周",
    category: "工作实习",
    description: "练习专业英文邮件写作，掌握各种场景的邮件表达。",
    suitableFor: ["英文邮件写不好", "不知道邮件怎么写才专业", "想提升书面表达"],
    weeklyGoal: "掌握 8 种场景的邮件模板和常用表达",
    dailyAction: "每天学习和改写一个场景的邮件（申请/询问/回复/感谢/道歉等）",
    minimumStandard: "每天至少写一封完整邮件",
    checkInType: "次数",
    reviewQuestions: ["哪种场景的邮件最难写？", "邮件表达有进步吗？", "积累的邮件模板实用吗？"],
    tags: ["邮件", "写作", "职场"],
    icon: "Mail",
    color: "#EC4899",
  },
  // ═══════════════════════════════════════════════════════════
  // 省钱理财
  // ═══════════════════════════════════════════════════════════
  {
    id: "save-money-week",
    title: "省钱周",
    category: "省钱理财",
    description: "控制不必要的开支，养成储蓄习惯。",
    suitableFor: ["月月光存不下钱", "想开始存钱但不知道从哪省", "消费冲动强"],
    weeklyGoal: "本周支出控制在预算的 80% 以内，存下收入的 10%",
    dailyAction: "每天记录每一笔支出，睡前问自己「今天这笔钱有必要花吗？」",
    minimumStandard: "每天至少记账",
    checkInType: "达标/未达标",
    reviewQuestions: ["这周最大的开支是什么？", "哪些钱其实可以不花？", "省钱过程中最大的挑战是什么？"],
    tags: ["省钱", "储蓄", "理财"],
    icon: "PiggyBank",
    color: "#10B981",
  },
  {
    id: "no-shopping-week",
    title: "不乱买周",
    category: "省钱理财",
    description: "本周不买任何非必需品，对抗消费主义。",
    suitableFor: ["经常冲动购物", "买了东西用不上", "想控制购物欲"],
    weeklyGoal: "整周不购买非必需品（只买食物和日用品）",
    dailyAction: "每次想买东西时等待 24 小时再做决定",
    minimumStandard: "非必需品零购买",
    checkInType: "达标/未达标",
    reviewQuestions: ["哪次购物冲动最难抵抗？", "不买东西的日子感觉如何？", "以后怎么控制购物欲？"],
    tags: ["省钱", "消费", "控制"],
    icon: "ShoppingBag",
    color: "#34D399",
  },
  {
    id: "budget-week",
    title: "记账周",
    category: "省钱理财",
    description: "认真记录每一笔收支，看清自己的钱花在哪里。",
    suitableFor: ["不知道钱花哪了", "想开始理财第一步", "消费没有规划"],
    weeklyGoal: "完整记录本周所有收支，做出一份周度财务报告",
    dailyAction: "每天睡前记录当天所有收支，分类统计",
    minimumStandard: "每天至少记录主要开支",
    checkInType: "达标/未达标",
    reviewQuestions: ["本周总收入支出结构是怎样的？", "哪类开支最大？有没有意外发现？", "根据记账结果下周想调整什么？"],
    tags: ["记账", "理财", "规划"],
    icon: "Notebook",
    color: "#6EE7B7",
  },
  {
    id: "less-takeout-week",
    title: "外卖减少周",
    category: "省钱理财",
    description: "减少点外卖的次数，省钱又健康。",
    suitableFor: ["天天点外卖", "外卖支出占比大", "想开始自己做饭"],
    weeklyGoal: "外卖次数控制在 3 次以内",
    dailyAction: "提前一天准备第二天的饭，或去食堂/便利店",
    minimumStandard: "外卖不超过 4 次",
    checkInType: "次数",
    reviewQuestions: ["减少外卖后省了多少钱？", "自己准备食物麻烦吗？", "以后每周点几次外卖比较合理？"],
    tags: ["省钱", "外卖", "健康"],
    icon: "Package",
    color: "#22C55E",
  },
  {
    id: "less-milk-tea-week",
    title: "奶茶控制周",
    category: "省钱理财",
    description: "减少奶茶和饮料消费，省钱又健康。",
    suitableFor: ["每天一杯奶茶/咖啡", "饮料开支不小", "想减少糖分摄入"],
    weeklyGoal: "本周奶茶/咖啡不超过 2 杯",
    dailyAction: "想喝奶茶时先喝一杯水，等 10 分钟再决定",
    minimumStandard: "比上周减少 50%",
    checkInType: "杯数",
    reviewQuestions: ["戒奶茶最难的是什么时候？", "省了多少钱？", "感觉身体有什么变化？"],
    tags: ["省钱", "奶茶", "健康"],
    icon: "CupSoda",
    color: "#F97316",
  },
  {
    id: "inventory-week",
    title: "清库存周",
    category: "省钱理财",
    description: "消耗家里已有的食物和物品，减少浪费。",
    suitableFor: ["冰箱里东西放很久了", "囤积了很多日用品", "想清理家中库存"],
    weeklyGoal: "消耗完冰箱里的食材，用完 3 件囤积物品",
    dailyAction: "每天检查并消耗一样库存物品，做饭优先用已有食材",
    minimumStandard: "每天至少消耗一样库存",
    checkInType: "件数",
    reviewQuestions: ["清理出了哪些快要过期的物品？", "以后还会囤积吗？", "清库存后家里空间有什么变化？"],
    tags: ["省钱", "清理", "不浪费"],
    icon: "Box",
    color: "#F59E0B",
  },
  {
    id: "budget-plan-week",
    title: "预算周",
    category: "省钱理财",
    description: "制定下周预算并严格执行，学会规划开支。",
    suitableFor: ["花钱没有计划", "想更好地管理财务", "经常超支"],
    weeklyGoal: "制定并执行下周预算，偏差不超过 10%",
    dailyAction: "早上查看今日预算额度，晚上核对实际支出",
    minimumStandard: "每天跟踪预算执行情况",
    checkInType: "达标/未达标",
    reviewQuestions: ["预算制定合理吗？", "哪项支出最容易超预算？", "预算管理对消费行为有什么影响？"],
    tags: ["预算", "理财", "规划"],
    icon: "Wallet",
    color: "#8B5CF6",
  },
  {
    id: "low-cost-happy-week",
    title: "低消费快乐周",
    category: "省钱理财",
    description: "发现不花钱或少花钱也能获得的快乐。",
    suitableFor: ["觉得快乐需要花钱", "想体验简单生活", "想减少物质依赖"],
    weeklyGoal: "体验 5 种免费/低成本的快乐活动",
    dailyAction: "每天做一件不花钱但让自己快乐的事（看夕阳/逛公园/听播客/写日记等）",
    minimumStandard: "每天至少发现一件免费的开心事",
    checkInType: "次数",
    reviewQuestions: ["最让你快乐的免费活动是什么？", "快乐和花钱之间真的有必然联系吗？", "以后会更多尝试低消费快乐吗？"],
    tags: ["省钱", "快乐", "简单生活"],
    icon: "Sun",
    color: "#FBBF24",
  },
  // ═══════════════════════════════════════════════════════════
  // 城市探索
  // ═══════════════════════════════════════════════════════════
  {
    id: "city-park-week",
    title: "公园周",
    category: "城市探索",
    description: "打卡城市里的公园或绿色空间，享受户外时光。",
    suitableFor: ["整天待在室内", "想探索所在城市", "想多接触自然"],
    weeklyGoal: "探索 3 个没去过的公园或绿地",
    dailyAction: "每天去一个公园散步/跑步/野餐/发呆 30 分钟以上",
    minimumStandard: "每周至少去 2 个公园",
    checkInType: "次数",
    reviewQuestions: ["最喜欢的公园是哪个？", "公园和城市其他空间有什么不同感受？", "以后会保持逛公园的习惯吗？"],
    tags: ["公园", "城市", "户外"],
    icon: "Trees",
    color: "#22C55E",
  },
  {
    id: "morning-market-week",
    title: "早市周",
    category: "城市探索",
    description: "早起去逛早市或菜市场，感受城市的烟火气。",
    suitableFor: ["没逛过早市", "想体验当地生活气息", "周末不知道做什么"],
    weeklyGoal: "逛 2 次不同的早市/菜市场",
    dailyAction: "早起去附近的早市或菜市场逛逛，买点新鲜食材",
    minimumStandard: "每周至少逛 1 次",
    checkInType: "次数",
    reviewQuestions: ["逛早市和逛超市的感觉有什么不同？", "发现了什么有趣的摊位或食材？", "早市上感受到的城市生活气息怎么样？"],
    tags: ["早市", "城市", "生活气息"],
    icon: "Store",
    color: "#F97316",
  },
  {
    id: "urban-village-week",
    title: "城中村探索周",
    category: "城市探索",
    description: "探索城市的城中村，发现不一样的城市面貌和美食。",
    suitableFor: ["对城市的不同面貌好奇", "想发现便宜好吃的店", "想拍人文照片"],
    weeklyGoal: "探索 2 个城中村，发现 3 家小店",
    dailyAction: "每天探索一个城中村或社区，记录看到的和吃到的",
    minimumStandard: "每周至少探索 1 个城中村",
    checkInType: "次数",
    reviewQuestions: ["城中村和你想象中有什么不同？", "最惊喜的发现是什么？", "城中村让你对城市有什么新认识？"],
    tags: ["探索", "城市", "人文"],
    icon: "Building",
    color: "#64748B",
  },
  {
    id: "cafe-study-week",
    title: "咖啡馆学习周",
    category: "城市探索",
    description: "在不同的咖啡馆学习和工作，换个环境换种心情。",
    suitableFor: ["学习/工作效率低", "想换个环境", "喜欢咖啡馆氛围"],
    weeklyGoal: "在 4 家不同的咖啡馆完成学习/工作任务",
    dailyAction: "每天去一家咖啡馆，带上电脑或书本待 2 小时",
    minimumStandard: "每周至少去 2 家咖啡馆",
    checkInType: "次数",
    reviewQuestions: ["哪家咖啡馆效率最高？", "环境和效率之间的关系是什么？", "以后会定期去咖啡馆工作/学习吗？"],
    tags: ["咖啡馆", "学习", "效率"],
    icon: "Coffee",
    color: "#D97706",
  },
  {
    id: "metro-explore-week",
    title: "地铁探索周",
    category: "城市探索",
    description: "坐地铁去没去过的地方，像旅行一样探索自己的城市。",
    suitableFor: ["每天两点一线", "想探索城市但没动力", "周末不知道去哪"],
    weeklyGoal: "坐地铁探索 3 个没去过的站点/区域",
    dailyAction: "每天选一个没去过的地铁站下车，在附近逛 1 小时",
    minimumStandard: "每周至少探索 2 个新地点",
    checkInType: "次数",
    reviewQuestions: ["哪个地铁站附近最让人惊喜？", "探索过程中有什么有趣的发现？", "坐地铁漫无目的地逛是什么感觉？"],
    tags: ["地铁", "探索", "冒险"],
    icon: "Train",
    color: "#3B82F6",
  },
  {
    id: "neighborhood-walk-week",
    title: "周边散步周",
    category: "城市探索",
    description: "在自己熟悉的周边走一走，发现平时忽略的风景和店铺。",
    suitableFor: ["每天走同样的路", "想重新认识自己住的地方", "想放松散步"],
    weeklyGoal: "发现 5 个之前没注意到的周边小店/风景",
    dailyAction: "每天换一条不同的路散步，留意周边细节",
    minimumStandard: "每天至少散步 15 分钟",
    checkInType: "时长(分钟)",
    reviewQuestions: ["发现了哪些平时忽略的风景？", "常走的和没走过的路有什么不同？", "对生活的地方有新的认识吗？"],
    tags: ["散步", "周边", "发现"],
    icon: "Map",
    color: "#10B981",
  },
  {
    id: "gz-food-week",
    title: "广州美食周",
    category: "城市探索",
    description: "探索广州的美食路线，吃遍地道小吃和隐藏餐厅。",
    suitableFor: ["在广州生活但不了解美食", "想发现好吃的店", "喜欢探索美食"],
    weeklyGoal: "尝试 5 家新餐厅/小吃店，找到 2 家会再去的",
    dailyAction: "每天去一个不同的区域探索美食（老城区/大学城/美食街/社区店）",
    minimumStandard: "每周至少尝试 3 家新店",
    checkInType: "次数",
    reviewQuestions: ["本周最佳美食发现是什么？", "哪个区域的美食最丰富？", "广州美食给你的最大感受是什么？"],
    tags: ["广州", "美食", "探索"],
    icon: "UtensilsCrossed",
    color: "#EF4444",
  },
  {
    id: "market-week",
    title: "菜市场周",
    category: "城市探索",
    description: "逛不同的菜市场，认识食材，感受生活本来的样子。",
    suitableFor: ["没去过菜市场", "喜欢烹饪但只用超市买食材", "想感受市井生活"],
    weeklyGoal: "逛 3 个不同的菜市场，认识 5 种新食材",
    dailyAction: "去一个菜市场逛逛，和摊主聊两句，买点没吃过的食材",
    minimumStandard: "每周至少逛 1 个菜市场",
    checkInType: "次数",
    reviewQuestions: ["菜市场和你想象中有什么不同？", "买了什么没吃过的食材？好吃吗？", "菜市场的氛围给你什么感受？"],
    tags: ["菜市场", "食材", "生活"],
    icon: "ShoppingBasket",
    color: "#F59E0B",
  },
  // ═══════════════════════════════════════════════════════════
  // 低能量恢复
  // ═══════════════════════════════════════════════════════════
  {
    id: "low-energy-week",
    title: "低能量周",
    category: "低能量恢复",
    description: "承认自己能量不足，做最少的事，不勉强自己。",
    suitableFor: ["最近很累没什么能量", "什么都不想做", "对自己要求太高了"],
    weeklyGoal: "每天完成 1 件「必须做」的事就够了",
    dailyAction: "每天选 1 件最重要的事完成，其余时间允许自己休息",
    minimumStandard: "每天至少做一件事（洗脸/吃饭/出门也算）",
    checkInType: "件数",
    reviewQuestions: ["一周只做必需的事感觉如何？", "其实最低限度生活也能过得去，对吗？", "能量恢复后最想做的是什么？"],
    tags: ["低能量", "恢复", "温柔"],
    icon: "BatteryLow",
    color: "#94A3B8",
  },
  {
    id: "recovery-week",
    title: "恢复周",
    category: "低能量恢复",
    description: "像养病一样养自己，吃好睡好，等能量慢慢回来。",
    suitableFor: ["身心俱疲", "刚经历压力期/生病", "需要彻底休息"],
    weeklyGoal: "每天睡够 8 小时，吃营养的饭菜，不做消耗的事",
    dailyAction: "好好吃饭、好好睡觉、做一件让自己舒服的事",
    minimumStandard: "每天保证充足睡眠和正常饮食",
    checkInType: "达标/未达标",
    reviewQuestions: ["一周恢复后感觉怎么样？", "哪件事最让你感觉被治愈？", "以后怎么预防自己再次透支？"],
    tags: ["恢复", "休息", "疗愈"],
    icon: "Heart",
    color: "#F43F5E",
  },
  {
    id: "slow-mo-week",
    title: "慢慢来周",
    category: "低能量恢复",
    description: "做什么事都慢一点，不赶时间，不给自己压力。",
    suitableFor: ["总觉得时间不够用", "做事很急", "想体验慢生活"],
    weeklyGoal: "不设任何时限，按自己的节奏完成所有事",
    dailyAction: "做什么都不赶，慢一点吃饭、慢一点走路、慢一点思考",
    minimumStandard: "每天至少有一件事是慢慢做的",
    checkInType: "时长(分钟)",
    reviewQuestions: ["慢下来是什么感受？", "其实慢一点也不会耽误什么，对吗？", "以后怎么在快节奏中保留慢的权利？"],
    tags: ["慢生活", "减压", "当下"],
    icon: "TimerOff",
    color: "#A8A29E",
  },
  {
    id: "just-a-little-week",
    title: "只做一点周",
    category: "低能量恢复",
    description: "用最小的行动维持生活秩序，做一点点就够了。",
    suitableFor: ["动不起来", "任务太多太有压力", "需要降低对自己的要求"],
    weeklyGoal: "每天完成最小单位的任务（如「只做 1 个俯卧撑」「只看 1 页书」）",
    dailyAction: "选一件事，告诉自己「只做 5 分钟」，做完就可以停",
    minimumStandard: "每天至少做一件「微小行动」",
    checkInType: "件数",
    reviewQuestions: ["「只做一点」的策略有没有让你更容易开始？", "做了之后会不会其实做了更多？", "以后怎么用这个方法来对抗拖延？"],
    tags: ["微小行动", "低压力", "开始"],
    icon: "ChevronRight",
    color: "#CBD5E1",
  },
  {
    id: "not-crash-week",
    title: "不崩溃周",
    category: "低能量恢复",
    description: "在压力中稳住自己，确保本周不崩溃就是胜利。",
    suitableFor: ["处于高压状态", "情绪濒临崩溃", "需要给自己喘息的空间"],
    weeklyGoal: "找到 3 个情绪出口，确保本周不会崩溃",
    dailyAction: "每天做一件照顾自己的事，识别情绪信号及早干预",
    minimumStandard: "每天至少做一次情绪检查",
    checkInType: "达标/未达标",
    reviewQuestions: ["这周坚持下来最大的支持是什么？", "哪些信号提醒你需要停下来？", "下次再遇到高压情况你会怎么应对？"],
    tags: ["情绪", "压力", "自救"],
    icon: "Shield",
    color: "#F87171",
  },
  {
    id: "catch-up-sleep-week",
    title: "补觉周",
    category: "低能量恢复",
    description: "把欠的睡眠补回来，睡到自然醒。",
    suitableFor: ["长期睡眠不足", "每天都很困", "想好好睡一觉"],
    weeklyGoal: "每天睡到自然醒，累计睡眠时间 56 小时以上",
    dailyAction: "不设闹钟，困了就睡，睡到自然醒",
    minimumStandard: "比平时多睡 1 小时",
    checkInType: "时长(小时)",
    reviewQuestions: ["睡够了之后身体和心情有什么变化？", "你其实需要多少小时睡眠？", "以后怎么保证不欠睡眠债？"],
    tags: ["睡眠", "补觉", "恢复"],
    icon: "Bed",
    color: "#6B7280",
  },
  {
    id: "life-baseline-week",
    title: "生活保底周",
    category: "低能量恢复",
    description: "只维持生活的基本运转，降低期待，先活下来再说。",
    suitableFor: ["状态非常差", "日常维持都有困难", "需要最低限度地活着"],
    weeklyGoal: "每天完成：吃饭、洗漱、出门一次、和人说一句话",
    dailyAction: "最低标准清单：吃饭→洗漱→换衣服→出门走 5 分钟→回消息",
    minimumStandard: "完成最基本的生理和生活需求",
    checkInType: "达标/未达标",
    reviewQuestions: ["最低标准生活能维持吗？", "感觉最困难的是哪一步？", "你觉得什么时候会好起来？"],
    tags: ["保底", "生存", "温柔"],
    icon: "LifeBuoy",
    color: "#9CA3AF",
  },
  {
    id: "gentle-restart-week",
    title: "温柔重启周",
    category: "低能量恢复",
    description: "在低迷期之后，温柔地重新开始，不责备自己。",
    suitableFor: ["经历低谷后想重新开始", "对自己之前的状态感到内疚", "需要温柔地重启生活"],
    weeklyGoal: "建立 3 个小而确定的积极习惯",
    dailyAction: "每天做一件让自己感觉「我在变好」的小事",
    minimumStandard: "每天至少做一件积极的事",
    checkInType: "件数",
    reviewQuestions: ["哪些小事让你感到「在变好」？", "这周你对自己温柔了吗？", "重启后的你有哪些新的认识？"],
    tags: ["重启", "温柔", "新生"],
    icon: "Sprout",
    color: "#34D399",
  },
];

export const CATEGORIES = [
  "学习成长",
  "英语提升",
  "AI与技能",
  "健康运动",
  "养生作息",
  "情绪疗愈",
  "生活整理",
  "兴趣探索",
  "社交关系",
  "工作实习",
  "省钱理财",
  "城市探索",
  "低能量恢复",
] as const satisfies readonly ThemeCategory[];

export const CATEGORY_ICONS: Record<ThemeCategory, string> = {
  "学习成长": "BookOpen",
  "英语提升": "Languages",
  "AI与技能": "Bot",
  "健康运动": "Activity",
  "养生作息": "Moon",
  "情绪疗愈": "HeartHandshake",
  "生活整理": "Home",
  "兴趣探索": "Paintbrush",
  "社交关系": "Users",
  "工作实习": "Briefcase",
  "省钱理财": "PiggyBank",
  "城市探索": "Map",
  "低能量恢复": "BatteryLow",
};

// ── Status / mood → recommended themes ──
import type { UserMood } from "./types";

export const MOOD_TO_THEMES: Record<UserMood, string[]> = {
  tired: ["low-energy-week", "recovery-week", "early-sleep-week", "slow-mo-week"],
  wantDiscipline: ["early-rise-week", "review-week", "exercise-week", "library-week"],
  wantStudy: ["reading-week", "preview-week", "review-week", "output-week"],
  wantEnglish: ["english-input-week", "speaking-week", "chunks-week", "tv-english-week"],
  wantHealth: ["exercise-week", "walking-week", "stretching-week", "park-week"],
  wantFun: ["park-week", "handcraft-week", "photography-week", "cafe-week"],
  wantOrganize: ["room-organization-week", "declutter-week", "phone-cleanup-week", "desk-cleanup-week"],
  wantJob: ["resume-optimize-week", "interview-prep-week", "trade-study-week", "portfolio-week"],
};

export const MOOD_LABELS: Record<UserMood, string> = {
  tired: "最近很累，没什么能量",
  wantDiscipline: "想变自律一点",
  wantStudy: "想提升学习效率",
  wantEnglish: "想提升英语",
  wantHealth: "想身体更健康",
  wantFun: "想生活更有趣",
  wantOrganize: "想整理房间和生活",
  wantJob: "想为实习/求职做准备",
};

export function getThemeById(id: string): ThemeTemplate | undefined {
  return THEME_TEMPLATES.find((t) => t.id === id);
}

export function getRecommendedThemeIds(): string[] {
  return ["low-energy-week", "english-input-week", "ai-learning-week", "park-week", "room-organization-week"];
}

export function searchThemes(query: string): ThemeTemplate[] {
  const q = query.toLowerCase();
  return THEME_TEMPLATES.filter(
    (t) =>
      t.title.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.toLowerCase().includes(q)) ||
      t.category.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q),
  );
}
